name: build

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-updatetar
          restore-keys: |
            ${{ runner.os }}-buildx-updatetar

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: build-scripts/Dockerfile.ci
          load: true
          tags: ci_image:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          build-args: |
            NPM_TOKEN=${{ secrets.NPM_TOKEN }}
            GPG_PASSPHRASE=${{ secrets.GPG_PASSPHRASE }}
            GPG_PASSPHRASE_LICENSE=${{ secrets.GPG_PASSPHRASE_LICENSE }}

      - name: Extract artifact from Docker image
        run: |
          docker create --name extract_artifact ci_image:latest
          docker cp extract_artifact:/lamassu/lamassu-machine/build/codebase/update.tar ./update.tar
          docker rm extract_artifact

      - name: Encrypt update.tar with GPG
        run: |
          echo "${{ secrets.GPG_PASSPHRASE }}" | gpg --batch --yes --passphrase-fd 0 -c update.tar
          rm update.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: update.tar.gpg
          path: update.tar.gpg

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache 
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
